### ISSUE TITLE
npm ERR! code EMISSINGARG when installing the clinet

### ISSUE THREAD

**Issue by LukeKeywalker** [apollographql/odyssey-lift-off-part1#5]
Hello,

When installing the client for the `lift-off-part1` I get a following error:

```
$ npm install
loadDep:react-scripts → r ▄ ╢██████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine graphql@15.5.0: wanted: {"node":">= 10.x"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:zen-observable →  ▄ ╢██████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 4.15.0-140-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/projects/odyssey-lift-off-part1/client/npm-debug.log
```

OS: Ubuntu `18.04`
nodejs -v: `v8.10.0`
npm -v: `3.5.2`|

Nodejs and NPM have been installed with `apt-get install` from the Ubuntu repository.

Best regards

**Comment by LukeKeywalker** [comment]
I noticed the warning after submitting the issue:
```
WARN engine graphql@15.5.0: wanted: {"node":">= 10.x"} (current: {"node":"8.10.0","npm":"3.5.2"})
```
Ubuntu 18.04 ships with Nodejs 8, version 10.0 needs to be added from explicitly:

```
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
```
